In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('houseprice.csv',usecols=["SalePrice", "MSSubClass", "MSZoning", "LotFrontage", "LotArea",
                                         "Street", "YearBuilt", "LotShape", "1stFlrSF", "2ndFlrSF"]).dropna()  

In [4]:
df.shape  #1201 records ,10 Features

(1201, 10)

In [5]:
df.head() # salesprice is the depending feature here 

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0          60       RL         65.0     8450   Pave      Reg       2003   
1          20       RL         80.0     9600   Pave      Reg       1976   
2          60       RL         68.0    11250   Pave      IR1       2001   
3          70       RL         60.0     9550   Pave      IR1       1915   
4          60       RL         84.0    14260   Pave      IR1       2000   

   1stFlrSF  2ndFlrSF  SalePrice  
0       856       854     208500  
1      1262         0     181500  
2       920       866     223500  
3       961       756     140000  
4      1145      1053     250000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   object 
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   object 
 5   LotShape     1201 non-null   object 
 6   YearBuilt    1201 non-null   int64  
 7   1stFlrSF     1201 non-null   int64  
 8   2ndFlrSF     1201 non-null   int64  
 9   SalePrice    1201 non-null   int64  
dtypes: float64(1), int64(6), object(3)
memory usage: 103.2+ KB


In [10]:
for i in df.columns:
    print("Column name {} and unique values are {}".format(i,len(df[i].unique()))) #from all the columns I took Iam seeing how many unique values are present in each of my column
#from the below output MSSubclass,MS Zoning,Street and Lotshape are categorical 

Column name MSSubClass and unique values are 15
Column name MSZoning and unique values are 5
Column name LotFrontage and unique values are 110
Column name LotArea and unique values are 869
Column name Street and unique values are 2
Column name LotShape and unique values are 4
Column name YearBuilt and unique values are 112
Column name 1stFlrSF and unique values are 678
Column name 2ndFlrSF and unique values are 368
Column name SalePrice and unique values are 597


In [11]:
import datetime
datetime.datetime.now().year

2024

In [14]:
df['Total Years']=datetime.datetime.now().year-df['YearBuilt'] #To replace the yearbuilt with total number of years 

In [15]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0          60       RL         65.0     8450   Pave      Reg       2003   
1          20       RL         80.0     9600   Pave      Reg       1976   
2          60       RL         68.0    11250   Pave      IR1       2001   
3          70       RL         60.0     9550   Pave      IR1       1915   
4          60       RL         84.0    14260   Pave      IR1       2000   

   1stFlrSF  2ndFlrSF  SalePrice  Total Years  
0       856       854     208500           21  
1      1262         0     181500           48  
2       920       866     223500           23  
3       961       756     140000          109  
4      1145      1053     250000           24

In [16]:
df.drop("YearBuilt",axis=1,inplace=True) #dropping the yearbuilt as we got total years now

In [87]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', '1stFlrSF', '2ndFlrSF', 'SalePrice', 'Total Years'],
      dtype='object')

In [20]:
cat_features=["MSSubClass", "MSZoning", "Street", "LotShape"]  #categorical features all the features other than this are continous features 
out_feature="SalePrice" #Output Feature 

In [23]:
df["MSSubClass"].unique() #here in the below output I have all unique values in integer format I have to convert all this into categorical features
#to convert the unique integer values into categorical features I am using label encoding 

array([ 60,  20,  70,  50, 190,  45,  90, 120,  30,  80, 160,  75, 180,
        40,  85], dtype=int64)

In [24]:
from sklearn.preprocessing import LabelEncoder
lbl_encoders={}
lbl_encoders["MSSubClass"]=LabelEncoder()
lbl_encoders["MSSubClass"].fit_transform(df["MSSubClass"])#after applying label encoding we can see that all the above unique values are indexed 

array([5, 0, 5, ..., 6, 0, 0], dtype=int64)

In [25]:
lbl_encoders

{'MSSubClass': LabelEncoder()}

In [31]:
from sklearn.preprocessing import LabelEncoder
lbl_encoders={}
for feature in cat_features:
    lbl_encoders[feature]=LabelEncoder()
    df[feature]=lbl_encoders[feature].fit_transform(df[feature]) #here I applied label encoding to all my categorical features 
#The label encoding was done to do embedding ,to do embedding all the categorical features are need to be indexed 


In [32]:
df #In the below dataset we can see all the categorical features are indexed 

MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  1stFlrSF  \
0              5         3         65.0     8450       1         3       856   
1              0         3         80.0     9600       1         3      1262   
2              5         3         68.0    11250       1         0       920   
3              6         3         60.0     9550       1         0       961   
4              5         3         84.0    14260       1         0      1145   
...          ...       ...          ...      ...     ...       ...       ...   
1455           5         3         62.0     7917       1         3       953   
1456           0         3         85.0    13175       1         3      2073   
1457           6         3         66.0     9042       1         3      1188   
1458           0         3         68.0     9717       1         3      1078   
1459           0         3         75.0     9937       1         3      1256   

      2ndFlrSF  SalePrice  Total Years  
0          854     208500           21  
1            0     181500           48  
2          866     223500           23  
3          756     140000          109  
4         1053     250000           24  
...        ...        ...          ...  
1455       694     175000           25  
1456         0     210000           46  
1457      1152     266500           83  
1458         0     142125           74  
1459         0     147500           59  

[1201 rows x 10 columns]

In [37]:
### Stacking and Converting Into Tensors
import numpy as np
cat_features=np.stack([df['MSSubClass'],df['MSZoning'],df['Street'],df['LotShape']],1)
cat_features#Here I stacked all my categorical features as columns,the 1 in the above code represents that
#Iam doing this to convert all my categorical features by making them as an numpy array and after that  into tensors 

array([[5, 3, 1, 3],
       [0, 3, 1, 3],
       [5, 3, 1, 0],
       ...,
       [6, 3, 1, 3],
       [0, 3, 1, 3],
       [0, 3, 1, 3]], dtype=int64)

In [42]:
### Convert numpy to Tensors
import torch
cat_features=torch.tensor(cat_features,dtype=torch.int64) 
cat_features

C:\Users\TEJ SAI PRANAV REDDY\AppData\Local\Temp\ipykernel_14976\1875173645.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  cat_features=torch.tensor(cat_features,dtype=torch.int64)


tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [43]:
#### create continuous variable
cont_features=[]
for i in df.columns:
    if i in ["MSSubClass", "MSZoning", "Street", "LotShape","SalePrice"]:
        pass
    else:
        cont_features.append(i) #Here to consider all my continous features I implemented a for loop which excludes all categorical features 

In [44]:
cont_features

['LotFrontage', 'LotArea', '1stFlrSF', '2ndFlrSF', 'Total Years']

In [49]:
### Stacking continuous variable to a tensor
cont_values=np.stack([df[i].values for i in cont_features],axis=1)
cont_values=torch.tensor(cont_values,dtype=torch.float) #all categorical features are specified with integer where as for continous it should be specified with float
cont_values #Above I stacked all the categorical features in the same way I stacked all the continous variables here. 
#And after that I converted all the numpy arrays into tensors 

tensor([[   65.,  8450.,   856.,   854.,    21.],
        [   80.,  9600.,  1262.,     0.,    48.],
        [   68., 11250.,   920.,   866.,    23.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    83.],
        [   68.,  9717.,  1078.,     0.,    74.],
        [   75.,  9937.,  1256.,     0.,    59.]])

In [50]:
cont_values.dtype

torch.float32

In [51]:
### Dependent Feature 
y=torch.tensor(df['SalePrice'].values,dtype=torch.float).reshape(-1,1)
y#Here I converted the dependent feature as a tensor and I did reshape because we need a two dimensional array

tensor([[208500.],
        [181500.],
        [223500.],
        ...,
        [266500.],
        [142125.],
        [147500.]])

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   int64  
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   int64  
 5   LotShape     1201 non-null   int64  
 6   1stFlrSF     1201 non-null   int64  
 7   2ndFlrSF     1201 non-null   int64  
 8   SalePrice    1201 non-null   int64  
 9   Total Years  1201 non-null   int64  
dtypes: float64(1), int64(9)
memory usage: 103.2 KB


In [53]:
cat_features.shape,cont_values.shape,y.shape

(torch.Size([1201, 4]), torch.Size([1201, 5]), torch.Size([1201, 1]))

In [55]:
len(df['MSSubClass'].unique()) #Embedding starts from here 
#Embedding is only supposed to done for categorical features 

15

In [56]:
#### Embedding Size For Categorical columns
cat_dims=[len(df[col].unique()) for col in ["MSSubClass", "MSZoning", "Street", "LotShape"]] #here Iam just checking how many unique values are present 
#In each categorical feature 

In [60]:
cat_dims #In embedding the inputs are categorical features dimensions that is 15,5,2,4

[15, 5, 2, 4]

In [63]:
###output dimension should be setbased on input dimension(min(50,feature dimension/2))
embedding_dim= [(x, min(50, (x + 1) // 2)) for x in cat_dims]

In [67]:
embedding_dim #In the below code output we got is 8 that is calculated as min(15+1/2 =8 ) #These all are data preprocessing steps 

[(15, 8), (5, 3), (2, 1), (4, 2)]

In [69]:

import torch
import torch.nn as nn
import torch.nn.functional as F
embed_representation=nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim]) #we use module list here because we have multiple dimensions 
embed_representation #here I just created a module list  to see what kind of vectors iam getting 

ModuleList(
  (0): Embedding(15, 8)
  (1): Embedding(5, 3)
  (2): Embedding(2, 1)
  (3): Embedding(4, 2)
)

In [139]:
cat_features

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [70]:
cat_featuresz=cat_features[:4]
cat_featuresz #iam doing embedding to only top four of my categorical features so I indexed it like that 

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        [6, 3, 1, 0]])

In [71]:
pd.set_option('display.max_rows', 500)
embedding_val=[] #here I created a list 
for i,e in enumerate(embed_representation):
    embedding_val.append(e(cat_features[:,i])) #The module features I had I converted all of them into vectors 

In [83]:
embedding_val#To understand the below output in clear if you take cat_features output the first column is 5,0,5,6 and the output is 8 dimensions
# so the embedding created 8 vectors 

[tensor([[ 0.1642,  0.0829,  1.1666,  ...,  0.1243,  0.2881, -0.5378],
         [ 0.4815,  1.1371, -1.6158,  ...,  0.0414,  1.0021, -0.9634],
         [ 0.1642,  0.0829,  1.1666,  ...,  0.1243,  0.2881, -0.5378],
         ...,
         [ 0.8517,  0.4354, -0.8424,  ..., -0.1143,  1.2039, -1.6079],
         [ 0.4815,  1.1371, -1.6158,  ...,  0.0414,  1.0021, -0.9634],
         [ 0.4815,  1.1371, -1.6158,  ...,  0.0414,  1.0021, -0.9634]],
        grad_fn=<EmbeddingBackward0>),
 tensor([[-2.1012,  0.3745, -1.2470],
         [-2.1012,  0.3745, -1.2470],
         [-2.1012,  0.3745, -1.2470],
         ...,
         [-2.1012,  0.3745, -1.2470],
         [-2.1012,  0.3745, -1.2470],
         [-2.1012,  0.3745, -1.2470]], grad_fn=<EmbeddingBackward0>),
 tensor([[-0.9180],
         [-0.9180],
         [-0.9180],
         ...,
         [-0.9180],
         [-0.9180],
         [-0.9180]], grad_fn=<EmbeddingBackward0>),
 tensor([[ 1.5920, -0.6318],
         [ 1.5920, -0.6318],
         [-0.9684, -0.

In [75]:
z = torch.cat(embedding_val, 1)
z#in the above output even if we get a proper output it was not stacked in a proper way to stack it in a proper way I concatenated here columnwise

tensor([[ 0.1642,  0.0829,  1.1666,  ..., -0.9180,  1.5920, -0.6318],
        [ 0.4815,  1.1371, -1.6158,  ..., -0.9180,  1.5920, -0.6318],
        [ 0.1642,  0.0829,  1.1666,  ..., -0.9180, -0.9684, -0.4804],
        ...,
        [ 0.8517,  0.4354, -0.8424,  ..., -0.9180,  1.5920, -0.6318],
        [ 0.4815,  1.1371, -1.6158,  ..., -0.9180,  1.5920, -0.6318],
        [ 0.4815,  1.1371, -1.6158,  ..., -0.9180,  1.5920, -0.6318]],
       grad_fn=<CatBackward0>)

In [76]:
#### Implement dropupout
droput=nn.Dropout(.4) #Iam using a droupout layer here to avoid overfitting

In [154]:
final_embed=droput(z)
final_embed

tensor([[ 0.0000, -3.9777, -1.8981,  ...,  1.2824,  0.0000, -0.0000],
        [ 1.0840,  0.0000,  0.0000,  ...,  1.2824,  0.0000, -1.7834],
        [ 1.1572, -3.9777, -1.8981,  ...,  0.0000, -0.0000, -0.0000],
        ...,
        [ 0.0000,  1.2390, -1.6782,  ...,  0.0000,  0.0000, -0.0000],
        [ 0.0000,  0.7187,  3.5020,  ...,  0.0000,  0.6231, -1.7834],
        [ 0.0000,  0.7187,  3.5020,  ...,  1.2824,  0.0000, -0.0000]],
       grad_fn=<MulBackward0>)

In [77]:
##### Create a Feed Forward Neural Network
import torch
import torch.nn as nn
import torch.nn.functional as F
class FeedForwardNN(nn.Module): # I defined my class here as feedforward neural network #I used nn.module because I can inherit the neural network 

    def __init__(self, embedding_dim, n_cont, out_sz, layers, p=0.5): #I had defined two functions here one is def and another is def forward and p is my dropout ratio.
        super().__init__() #we have to do this step to inherit all the parameters from nn.module
        self.embeds = nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim])
        self.emb_drop = nn.Dropout(p)
        self.bn_cont = nn.BatchNorm1d(n_cont)
        
        layerlist = []
        n_emb = sum((out for inp,out in embedding_dim)) #number of embedding dimensions 
        n_in = n_emb + n_cont #number of inputs 
        
        for i in layers:
            layerlist.append(nn.Linear(n_in,i)) 
            layerlist.append(nn.ReLU(inplace=True))
            layerlist.append(nn.BatchNorm1d(i))
            layerlist.append(nn.Dropout(p))
            n_in = i
        layerlist.append(nn.Linear(layers[-1],out_sz))
            
        self.layers = nn.Sequential(*layerlist)
    
    def forward(self, x_cat, x_cont):
        embeddings = []
        for i,e in enumerate(self.embeds):
            embeddings.append(e(x_cat[:,i]))
        x = torch.cat(embeddings, 1)
        x = self.emb_drop(x)
        
        x_cont = self.bn_cont(x_cont)
        x = torch.cat([x, x_cont], 1)
        x = self.layers(x)
        return x

In [158]:
len(cont_features)

5

In [79]:
torch.manual_seed(100)
model=FeedForwardNN(embedding_dim,len(cont_features),1,[100,50],p=0.4)

In [80]:
model

FeedForwardNN(
  (embeds): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=19, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)

In [82]:
loss_function=nn.MSELoss() #later I will convert this into RMSE
optimizer=torch.optim.Adam(model.parameters(),lr=0.01)

In [165]:
df.shape

(1201, 10)

In [167]:
cont_values

tensor([[   65.,  8450.,   856.,   854.,    21.],
        [   80.,  9600.,  1262.,     0.,    48.],
        [   68., 11250.,   920.,   866.,    23.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    83.],
        [   68.,  9717.,  1078.,     0.,    74.],
        [   75.,  9937.,  1256.,     0.,    59.]])

In [169]:
cont_values.shape

torch.Size([1201, 5])

In [171]:
#Train_test_split
batch_size=1200
test_size=int(batch_size*0.15)
train_categorical=cat_features[:batch_size-test_size]
test_categorical=cat_features[batch_size-test_size:batch_size]
train_cont=cont_values[:batch_size-test_size]
test_cont=cont_values[batch_size-test_size:batch_size]
y_train=y[:batch_size-test_size]
y_test=y[batch_size-test_size:batch_size]

In [173]:
len(train_categorical),len(test_categorical),len(train_cont),len(test_cont),len(y_train),len(y_test)

(1020, 180, 1020, 180, 1020, 180)

In [175]:
epochs=5000
final_losses=[]
for i in range(epochs):
    i=i+1
    y_pred=model(train_categorical,train_cont)
    loss=torch.sqrt(loss_function(y_pred,y_train)) ### RMSE
    final_losses.append(loss)
    if i%10==1:
        print("Epoch number: {} and the loss : {}".format(i,loss.item()))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch number: 1 and the loss : 34328.66015625
Epoch number: 11 and the loss : 34355.61328125
Epoch number: 21 and the loss : 36025.62109375
Epoch number: 31 and the loss : 35257.1328125
Epoch number: 41 and the loss : 33742.0546875
Epoch number: 51 and the loss : 34964.05078125
Epoch number: 61 and the loss : 35146.73046875
Epoch number: 71 and the loss : 33501.05078125
Epoch number: 81 and the loss : 35852.77734375
Epoch number: 91 and the loss : 35827.5625
Epoch number: 101 and the loss : 35341.2578125
Epoch number: 111 and the loss : 35029.2421875
Epoch number: 121 and the loss : 36387.01171875
Epoch number: 131 and the loss : 35523.30859375
Epoch number: 141 and the loss : 34857.22265625
Epoch number: 151 and the loss : 36218.39453125
Epoch number: 161 and the loss : 34842.39453125
Epoch number: 171 and the loss : 36076.34765625
Epoch number: 181 and the loss : 35437.78515625
Epoch number: 191 and the loss : 35347.546875
Epoch number: 201 and the loss : 35053.16015625
Epoch number:

In [177]:
#### Validate the Test Data
y_pred=""
with torch.no_grad():
    y_pred=model(test_categorical,test_cont)
    loss=torch.sqrt(loss_function(y_pred,y_test))
print('RMSE: {}'.format(loss))

RMSE: 45899.5625


In [179]:
data_verify=pd.DataFrame(y_test.tolist(),columns=["Test"])

In [181]:
data_predicted=pd.DataFrame(y_pred.tolist(),columns=["Prediction"])

In [184]:
data_predicted

Prediction
0    157620.859375
1    109154.914062
2    171355.703125
3    220284.359375
4    193250.671875
5    211570.546875
6    203497.093750
7    302878.625000
8    148640.593750
9    362125.906250
10   251606.234375
11   205394.796875
12   234192.859375
13   112551.851562
14   268338.156250
15   128826.835938
16   209843.484375
17   141096.296875
18   289030.437500
19    78536.703125
20   189581.671875
21   121491.367188
22   117318.554688
23   193231.671875
24   160906.406250
25   163867.750000
26   151816.437500
27   452136.156250
28   153394.687500
29   121840.765625
30    97033.039062
31   121595.585938
32   232132.203125
33   132157.171875
34   218714.484375
35   173551.359375
36   148905.375000
37   100665.812500
38   192867.234375
39   102220.843750
40   229617.453125
41   289295.750000
42   111506.195312
43   224857.953125
44   176836.062500
45   121376.101562
46   120955.843750
47   113592.875000
48   120923.984375
49   324658.937500
50   133605.609375
51   248856.578125
52   221802.640625
53   137802.296875
54   252018.640625
55   208662.046875
56   144426.265625
57   128816.218750
58   219201.671875
59   200998.078125
60   274353.937500
61   118771.851562
62   208730.765625
63   260582.328125
64   177186.250000
65   122858.015625
66   140886.031250
67   258370.500000
68    67132.773438
69   316140.562500
70    72691.773438
71    91475.382812
72    97356.781250
73   183339.968750
74   219886.734375
75   238720.562500
76   151008.187500
77    96162.570312
78    99591.859375
79   106710.593750
80   171526.265625
81   135604.640625
82    93670.554688
83   230997.046875
84   127371.078125
85   115989.648438
86   159657.671875
87   153841.906250
88   159192.484375
89   100344.812500
90   291342.625000
91   156799.859375
92   147697.796875
93   185375.921875
94    97216.492188
95   337164.406250
96   191048.000000
97   247120.921875
98   368088.781250
99   210587.125000
100  209047.359375
101  131358.703125
102  179928.296875
103  117150.109375
104  302470.906250
105  135951.468750
106  193788.781250
107  253051.828125
108  192643.171875
109  231174.312500
110   77693.968750
111  147540.984375
112   73474.679688
113  186025.234375
114   80759.851562
115  198433.593750
116   91022.929688
117   84663.500000
118  334955.250000
119  126609.039062
120  306544.687500
121   99363.085938
122  186767.734375
123  122635.906250
124  106793.851562
125  106123.117188
126  185799.765625
127  343462.750000
128  100578.507812
129  158455.968750
130  139582.140625
131   95143.789062
132  211064.765625
133  170624.234375
134  242908.062500
135  104321.843750
136  180059.765625
137   98651.304688
138  118743.281250
139  314963.343750
140  234008.015625
141  168685.203125
142  117717.101562
143  337494.437500
144  159506.031250
145  184590.703125
146   91918.882812
147  145802.640625
148  154397.921875
149  121991.398438
150  122003.304688
151  156288.437500
152  282024.468750
153  145657.578125
154   86833.960938
155  251594.187500
156  121866.539062
157  200567.265625
158  152986.687500
159  163817.515625
160  103615.937500
161  277887.562500
162  107888.960938
163  220308.796875
164  220093.109375
165  279361.062500
166  189921.421875
167  143904.453125
168  237058.296875
169  104144.953125
170   57272.988281
171  125529.007812
172  261687.015625
173  125735.632812
174  215406.937500
175  210820.484375
176  206406.203125
177  316896.187500
178  251108.328125
179  103088.921875

In [187]:
final_output=pd.concat([data_verify,data_predicted],axis=1)
final_output['Difference']=final_output['Test']-final_output['Prediction']
final_output.head()

Test     Prediction    Difference
0  130000.0  157620.859375 -27620.859375
1  138887.0  109154.914062  29732.085938
2  175500.0  171355.703125   4144.296875
3  195000.0  220284.359375 -25284.359375
4  142500.0  193250.671875 -50750.671875

In [189]:
#### Saving The Model
#### Save the model
torch.save(model,'HousePrice.pt')

In [191]:
torch.save(model.state_dict(),'HouseWeights.pt')

In [193]:
### Loading the saved Model
embs_size=[(15, 8), (5, 3), (2, 1), (4, 2)]
model1=FeedForwardNN(embs_size,5,1,[100,50],p=0.4)

In [194]:
model1.load_state_dict(torch.load('HouseWeights.pt'))

C:\Users\TEJ SAI PRANAV REDDY\AppData\Local\Temp\ipykernel_21960\2229105223.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model1.load_state_dict(torch.load('HouseWeigh

<All keys matched successfully>

In [196]:
model1.eval()

FeedForwardNN(
  (embeds): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=19, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)